#!/bin/bash

#SBATCH -p dl
#SBATCH --gres=gpu:v100:2
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=12
#SBATCH --time=2-00:00:00
#SBATCH -o data_out_%j.out
#SBATCH -e data_%j.err
#SBATCH --mail-user=anakuzne@iu.edu
#SBATCH --mail-type=ALL
#SBATCH -J Data

module swap python/2.7.16 deeplearning/1.13.1
module load deeplearning/1.13.1
module load libsndfile/1.0.28
cd /N/u/anakuzne/Carbonate/dl_for_speech/HW3_II

python save_data.py